### PR TITLE
Support for Oraxen Custom Items durability

### PR DESCRIPTION
**Pull request by Mowstyl**
First of all, sorry for creating a new pull request. I accidentally deleted [the old one](https://github.com/Crazy-Crew/CrazyEnchantments/pull/664) when I renamed my master branch to main. My apologies.

I've updated the changes from [my previous pull request](https://github.com/Crazy-Crew/Crazy-Enchantments/pull/641) in order to be up to date with your repository.
These changes make the plugin check if an ItemStack is an Oraxen custom item and use the custom durability of that object instead of the vanilla one.

### CODE REVIEW

**Comment by RyderBelserion** [comment]
How much have you tested this?

**Comment by Mowstyl** [comment]
Normal usage of the plugin since December on my server with no complaints from any player/staff.
I've checked that hellforged works well for both vanilla and oraxen items.
I haven't checked if the plugin works in older versions (versions older than the one that was out in December, I think 1.18), but I can do it if you need me to.
I think I tested that the plugin worked with and without oraxen installed, yet I don't remember what did I test back then.

**Comment by RyderBelserion** [comment]
Realistically if it works on 1.19, works on 1.18 but we don't need go out of our way to check it.

**Review by RyderBelserion — APPROVED** [review]
Looks pretty good here.

**Pull request merged**
